# Generated by Django 5.2.6 on 2026-09-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='name',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='count_of_servers_closed',
            field=models.IntegerField(null=True),
        ),
    ]
