# Generated by Django 5.2.6 on 2026-09-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_database_name_alter_database_count_of_servers_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
