# Generated by Django 5.2.6 on 2026-09-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_database_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='name',
        ),
    ]
